# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="blinks-asou"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(brew git git-flow github heroku command-coloring osx)

source $ZSH/oh-my-zsh.sh

# vim magic
bindkey -v

# backwards search
bindkey '^R' history-incremental-search-backward

EDITOR=vim
VISUAL=vim
GIT_EDITOR=vim

__git_files () { 
    _wanted files expl 'local files' _files     
}

# kudos to dvor
w() {
    dir="./"

    if [ ! -z $1 ]; then
        dir=$1
    fi

    workspaces=`ls $dir | grep xcworkspace`

    if [ -z "$workspaces" ]; then
        echo "No xcworkspace's found in directory $dir"
        exit 0
    fi

    if [ `echo "$workspaces" | wc -l` -eq 1 ]; then
        space=$workspaces
    else
        echo "Available xcworkspaces:"
        echo "$workspaces" | nl
        printf "Select xcworkspace> "

        read num

        space=`echo "$workspaces" | sed -n ${num}p`
    fi

    open $dir/$space
}

alias pi="pod install"

export LANG=en_US.UTF-8

alias be="bundle exec"

export LC_CTYPE=en_US.UTF-8

pdf() {
    project_folder="./"$1
    pandoc -V fontsize=12pt -o $1.pdf $1
    open $1.pdf
}

alias ksdiff=/Applications/p4merge.app/Contents/Resources/launchp4merge
